[package]
name = "multitakes_simul_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
rand = { version = "0.8", features = ["std", "small_rng"] }
rand_distr = "0.4"
statrs = "0.16"
rayon = "1.10"
